apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "bridge-main",
            "ips": ["192.168.12.10"]}]'
spec:
  nodeSelector:
    kubernetes.io/hostname: 10.110.198.122
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: another
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "bridge-main",
            "ips": ["192.168.12.11"]}]'
spec:
  nodeSelector:
    kubernetes.io/hostname: 10.110.198.122
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80