apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: fedora
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: fedora
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
                
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
      - name: fedora
        persistentVolumeClaim:
          claimName: fedora
      # - name: blockdisk
      #   dataVolume:
      #     name: fedora-blockdisk-1
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            hostname: fedora
            ssh_pwauth: True
            disable_root: false
            ssh_authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2YnDRdgURlnKgz6P9k3sMSWEFf/x8CW/iUlHk5SbUU+HqZFgNx8m0HjZq8JtiCuVzmppqu5zq1l4tX94qCmUPwxiCF8g/+FjC2s1EI0mD6f0C9CIZ+ZgZ7OPhlKEOs0l46XAfKA3jkzLSGEbxivSdo452UtWhEfzZPqS7n+NsHr4HbRgeIv2rFuvOb2koCETub7YcWyHKmm66izN9n+9d7Na7pCjyxQ6HKYdzNj0Sa/SmhMIVEUr0nXMEh0ywdhzwUoSjXHdsADY1N5P5rO+cqCsznKzpgIoflqVXvP63r830F3HevKY9p941vgegEIY77vkh0US9AevGP9lUPJXmCaRhg84kLuvbei6Vzaxl0pROSEQ9L4RaHlEBDs+KNIucCpcpfNOyZrcNCtvnd3tBSqqJK+JiNeFOmXU11udh8B1et9sWNUuRp4SmOCJ40b81vyJOaFxX8D+zT2H3C4O7p5st/XAqkWzJh9UUEh7wpQV6gSNxU+K4FcIHW6Q2CMU= supakorn.t@MacBook-Pro-khxng-Supakorn.local
        name: cloudinitdisk
  dataVolumeTemplates:
  - metadata:
      name: fedora
    spec:
      pvc:
        volumeMode: Block
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      source:
        pvc:
          namespace: thesis-virt
          name: fedora-iso-dv
  # - metadata:
  #     name: fedora-blockdisk-1
  #   spec:
  #       pvc:
  #         accessModes:
  #           - ReadWriteOnce
  #         resources:
  #           requests:
  #             storage: 30Gi
  #         storageClassName: managed-premium
  #         volumeMode: Block
  #       source:
  #         pvc:
  #           namespace: thesis-virt
  #           name: fedora-iso-dv