apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: database-server
  namespace: legacy-company
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: database-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-10.0.225.13.ap-southeast-1.compute.internal
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: disk0
            bootOrder: 2
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk
            bootOrder: 1
          interfaces:
            - name: default
              bridge: {}
            - name: database-server
              bridge: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      networks:
        - name: default
          pod: {}
        - name: database-server
          multus:
            networkName: database-server
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: database-server-block
      - name: cloudinitdisk
        cloudInitNoCloud:
          networkData: |
            version: 2
            ethernets:
              eth0: 
                dhcp4: true
  dataVolumeTemplates:
  - metadata:
      name: database-server-block
    spec:
      pvc:
        # volumeMode: block
        # storageClassName: managed-premium
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
      source:
        pvc:
          namespace: vm-images
          name: database-server-vm-dv