apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: fedora-nginx
  namespace: thesis-virt
  labels:
    kubevirt.io/os: linux
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: fedora
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      volumes:
        - name: fedora
          persistentVolumeClaim:
            claimName: fedora-blockdisk-nginx
        - cloudInitNoCloud:
            userData: >
              packages:
              - nginx
              - podman
              hostname: fedora
              users:
              - name: root
              - name: fedora 
                groups: users,wheel 
                ssh_pwauth: True 
              
              chpasswd:
                list: |
                  root: fedora
                  fedora: fedora
                expire: True

              

          name: cloudinitdisk
  dataVolumeTemplates:
    - metadata:
        name: fedora-blockdisk-nginx
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
          storageClassName: managed-premium
          volumeMode: Block
        source:
          pvc:
            name: fedora-iso-dv
            namespace: thesis-virt