kind: ConfigMap
apiVersion: v1
metadata:
  name: dns-config
  namespace: openshift-dns
data:
  Corefile: |
    napzz-thesis-chula.com:8053 {
        log stdout
        file /etc/coredns/napzz-thesis-chula.com
    }
  napzz-thesis-chula.com: |
    $TTL    1800
    $ORIGIN napzz-thesis-chula.com.

    @ IN SOA dns domains (
        2020031101   ; serial
        300          ; refresh
        1800         ; retry
        14400        ; expire
        300 )        ; minimum

    ;PRIVATE_DNS_RECORD
    portal       IN  A  10.110.198.99
    ;[1]ID: infra 
    infra        IN  A  172.30.167.100
    ;END_PRIVATE_DNS_RECORD

    ;portal       IN  A  10.110.198.38
    ;infra        IN  A  172.30.167.185