kind: Service
apiVersion: v1
metadata:
  name: dns-custom
  namespace: openshift-dns
  labels:
    app: dns
spec:
  ports:
    - name: 8053-tcp
      protocol: TCP
      port: 8053
      targetPort: 8053
    - name: 8053-udp
      protocol: UDP
      port: 8053
      targetPort: 8053
  selector:
    app: dns
    deployment: dns
  clusterIP: 172.21.103.99
  clusterIPs:
    - 172.21.103.99
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: {}
