apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: napzz-bridge-public-zone
  namespace: legacy-company
spec:
  config: >-
    { 
      "cniVersion": "0.3.1", 
      "type": "bridge", 
      "bridge": "bridge-public-zone", 
      "ipam": {
        "type": "host-local", 
        "subnet": "192.168.17.0/24", 
        "rangeStart": "192.168.17.1", 
        "rangeEnd": "192.168.17.254" 
        } 
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: napzz-bridge-secure-zone
  namespace: legacy-company
spec:
  config: >-
    { 
      "cniVersion": "0.3.1", 
      "type": "bridge", 
      "bridge": "bridge-secure-zone", 
      "ipam": {
        "type": "host-local", 
        "subnet": "192.168.18.0/24", 
        "rangeStart": "192.168.18.1", 
        "rangeEnd": "192.168.18.254" 
        } 
    }
---