kind: Deployment
apiVersion: apps/v1
metadata:
  name: bridge-secure
  labels:
    app: bridge-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-secure
  template:
    metadata:
      labels:
        app: bridge-secure
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "macvlan-secure"}]'
    spec:
      serviceAccountName: default
      containers:
        - name: bridge-secure
          image: "quay.io/linxianer12/nettool:0.0.4"
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - "NET_RAW"
                - "NET_ADMIN"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600