kind: Deployment
apiVersion: apps/v1
metadata:
  name: bridge-router
  labels:
    app: bridge-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-router
  template:
    metadata:
      labels:
        app: bridge-router
        tuned.openshift.io/kubevirt-network-operator: ""
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "macvlan-public"},{ "name": "macvlan-secure"}]'
    spec:
      nodeSelector:
        kubernetes.io/hostname: 10.111.147.173 # ต้องเป้นเครื่องตรงกลาง
      serviceAccountName: default
      volumes:
      - name: modifysys
        hostPath:
          path: /sys
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=1
            # - sysctl -w net.ipv4.ip_local_port_range="1025 65535"; sysctl -w net.core.somaxconn=32768;
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: modifysys
              mountPath: /sys
      containers:
        - name: bridge-router
          image: "quay.io/linxianer12/nettool:0.0.4"
          imagePullPolicy: Always
          securityContext:
            sysctls:
              - name: net.ipv4.ip_forward
                value: 1
            securityContext:
              privileged: true
            capabilities:
              add:
                - "NET_RAW"
                - "NET_ADMIN"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600