# apiVersion: policy/v1beta1
# kind: PodSecurityPolicy
# metadata:
#   name: sysctl-psp
#   namespace: legacy-company
# spec:
#   allowedUnsafeSysctls:
#   - net.ipv4.ip_forward


# apiVersion: tuned.openshift.io/v1
# kind: Tuned
# metadata:
#   name: kubevirt-network
#   namespace: openshift-cluster-node-tuning-operator
# spec:
#   profile:
#     - name: "kubevirt-network-operator"
#       data: |
#         [main]
#         summary=Optimize systems running ES on OpenShift nodes
#         include=openshift-node
#         [sysctl]
#         net.ipv4.ip_forward=1
#     - data: >
#         [main]

#         summary=Optimize systems running OpenShift (parent profile)

#         include=${f:virt_check:virtual-guest:throughput-performance}


#         [selinux]

#         avc_cache_threshold=8192


#         [net]

#         nf_conntrack_hashsize=131072


#         [sysctl]

#         net.ipv4.ip_forward=1

#         kernel.pid_max=>4194304

#         net.netfilter.nf_conntrack_max=1048576

#         net.ipv4.conf.all.arp_announce=2

#         net.ipv4.neigh.default.gc_thresh1=8192

#         net.ipv4.neigh.default.gc_thresh2=32768

#         net.ipv4.neigh.default.gc_thresh3=65536

#         net.ipv6.neigh.default.gc_thresh1=8192

#         net.ipv6.neigh.default.gc_thresh2=32768

#         net.ipv6.neigh.default.gc_thresh3=65536

#         vm.max_map_count=262144


#         [sysfs]

#         /sys/module/nvme_core/parameters/io_timeout=4294967295

#         /sys/module/nvme_core/parameters/max_retries=10


#         [scheduler]

#         # see rhbz#1998120; exclude containers from aligning to house keeping
#         CPUs

#         cgroup_ps_blacklist=/kubepods\.slice/

#         # workaround for rhbz#1921738

#         runtime=0
#       name: openshift
#     - data: |
#         [main]
#         summary=Optimize systems running OpenShift control plane
#         include=openshift

#         [sysctl]
#         # ktune sysctl settings, maximizing i/o throughput
#         #
#         # Minimal preemption granularity for CPU-bound tasks:
#         # (default: 1 msec#  (1 + ilog(ncpus)), units: nanoseconds)
#         kernel.sched_min_granularity_ns=10000000
#         # The total time the scheduler will consider a migrated process
#         # "cache hot" and thus less likely to be re-migrated
#         # (system default is 500000, i.e. 0.5 ms)
#         kernel.sched_migration_cost_ns=5000000
#         # SCHED_OTHER wake-up granularity.
#         #
#         # Preemption granularity when tasks wake up.  Lower the value to
#         # improve wake-up latency and throughput for latency critical tasks.
#         kernel.sched_wakeup_granularity_ns=4000000
#       name: openshift-control-plane
#     - data: |
#         [main]
#         summary=Optimize systems running OpenShift nodes
#         include=openshift
 
#         [sysctl]
#         net.ipv4.ip_forward=1
#         net.ipv4.tcp_fastopen=3
#         fs.inotify.max_user_watches=65536
#         fs.inotify.max_user_instances=8192
#       name: openshift-node
#   recommend:
#     - match:
#       - label: "tuned.openshift.io/kubevirt-network-operator"
#         type: "pod"
#       profile: "kubevirt-network-operator"
#       priority: 20
#     - match:
#         - label: node-role.kubernetes.io/master
#         - label: node-role.kubernetes.io/infra
#       operand:
#         debug: false
#       priority: 30
#       profile: openshift-control-plane
#     - operand:
#         debug: false
#       priority: 40
#       profile: openshift-node
# status: {}
