apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  nodeSelector:
    kubernetes.io/hostname: 10.110.198.105
  volumes:
    - name: modifysys
      hostPath:
        path: /sys
  initContainers:
    - command:
        - sh
        - -c
        - sysctl -w net.ipv4.ip_forward=1
        # - sysctl -w net.ipv4.ip_local_port_range="1025 65535"; sysctl -w net.core.somaxconn=32768;
      image: alpine:3.6
      imagePullPolicy: IfNotPresent
      name: sysctl
      resources: {}
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
      volumeMounts:
        - name: modifysys
          mountPath: /sys
  containers:
    - name: bridge-public
      image: "quay.io/linxianer12/nettool:0.0.4"
      imagePullPolicy: Always
      resources: {}
      securityContext:
        sysctls:
          - name: net.ipv4.ip_forward
            value: 1
          - name: kernel.shm_rmid_forced
            value: "0"
          - name: net.core.somaxconn
            value: "1024"
          - name: kernel.msgmax
            value: "65536"
        securityContext:
          privileged: true
        capabilities:
          add:
            - "NET_RAW"
            - "NET_ADMIN"
