apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: system:openshift:scc:ibm-privileged-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - ibm-privileged-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:ibm-privileged-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:ibm-privileged-scc
subjects:
- kind: ServiceAccount
  name: default
  namespace: legacy-company
