kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: static
  namespace: legacy-company
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "brse",
      "ipam": {
        "type": "static",
        "addresses": [
              {
                "address": "192.168.18.99/24"
              }
            ]
        }
    }
---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: backend-server
  namespace: legacy-company
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "brse",
      "ipam": {
        "type": "static",
        "addresses": [
              {
                "address": "192.168.18.4/24"
              }
            ]
        }
    }
---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: database-server
  namespace: legacy-company
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "brse",
      "ipam": {
        "type": "static",
        "addresses": [
              {
                "address": "192.168.18.5/24"
              }
            ]
        }
    }
---
kind: NetworkAttachmentDefinition
apiVersion: k8s.cni.cncf.io/v1
metadata:
  name: frontend-server
  namespace: legacy-company
spec:
  config: >-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "brse",
      "ipam": {
        "type": "static",
        "addresses": [
              {
                "address": "192.168.18.6/24"
              }
            ]
        }
    }