kind: Deployment
apiVersion: apps/v1
metadata:
  name: bridge-secure
  namespace: legacy-company
  labels:
    app: bridge-secure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-secure
  template:
    metadata:
      labels:
        app: bridge-secure
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "static"}]'
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: 10.111.147.210
      serviceAccountName: default
      volumes:
      - name: modifysys
        hostPath:
          path: /sys
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=0
            # - sysctl -w net.ipv4.ip_local_port_range="1025 65535"; sysctl -w net.core.somaxconn=32768;
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: modifysys
              mountPath: /sys      
      containers:
        - name: bridge-secure
          image: "quay.io/linxianer12/nettool:0.0.4"
          imagePullPolicy: Always
          securityContext:
            securityContext:
              privileged: true
            capabilities:
              add:
                - "NET_RAW"
                - "NET_ADMIN"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bridge-frontend
  namespace: legacy-company
  labels:
    app: bridge-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bridge-frontend
  template:
    metadata:
      labels:
        app: bridge-frontend
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "frontend-server"}]'
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: 10.111.147.210
      serviceAccountName: default
      volumes:
      - name: modifysys
        hostPath:
          path: /sys
      initContainers:
        - command:
            - sh
            - -c
            - sysctl -w net.ipv4.ip_forward=0
            # - sysctl -w net.ipv4.ip_local_port_range="1025 65535"; sysctl -w net.core.somaxconn=32768;
          image: alpine:3.6
          imagePullPolicy: IfNotPresent
          name: sysctl
          resources: {}
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: modifysys
              mountPath: /sys      
      containers:
        - name: bridge-secure
          image: "quay.io/linxianer12/nettool:0.0.4"
          imagePullPolicy: Always
          securityContext:
            securityContext:
              privileged: true
            capabilities:
              add:
                - "NET_RAW"
                - "NET_ADMIN"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600