apiVersion: nmstate.io/v1alpha1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: brse-ens5
spec:
  maxUnavailable: 1
  nodeSelector:
    custom-network: 'true'
  desiredState:
    interfaces:
    - name: brse
      description: Linux bridge with ens5 as a port
      type: linux-bridge
      state: up
      ipv4:
        dhcp: true
        enabled: true
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens5