apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: fedora-iso-dv
spec:
  source:
    pvc:
      name: fedora
      namespace: thesis-virt
    
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
