
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu20-cloud-img
  namespace: vm-images
spec:
  source:
    http:
      url: https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi