apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: ubuntu-iso-dv
spec:
  source:
    pvc:
      name: ubuntu20
      namespace: thesis-virt
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
