---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmstate-operator
  namespace: nmstate
  labels:
    app: kubernetes-nmstate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-nmstate-operator
  template:
    metadata:
      labels:
        app: kubernetes-nmstate-operator
        name: kubernetes-nmstate-operator
    spec:
      serviceAccountName: nmstate-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-cluster-critical
      containers:
        - name: nmstate-operator
          # Replace this with the built image name
          image: quay.io/nmstate/kubernetes-nmstate-operator:v0.64.13
          imagePullPolicy: Always
          command:
          - manager
          resources:
            requests:
              cpu: 60m
              memory: 30Mi
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "kubernetes-nmstate-operator"
            - name: ENABLE_PROFILER
              value: "False"
            - name: PROFILER_PORT
              value: "6060"
            - name: RUN_OPERATOR
              value: ""
            - name: RELATED_IMAGE_HANDLER_IMAGE
              value: quay.io/nmstate/kubernetes-nmstate-handler:v0.64.13
            - name: HANDLER_IMAGE_PULL_POLICY
              value: Always
            - name: HANDLER_NAMESPACE
              value: nmstate
