apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-sa-role-binding
  namespace: thesis-virt
  annotations:
    argocd.argoproj.io/sync-wave: "1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: argocd-cluster-argocd-application-controller
    namespace: thesis-virt
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: thesis-virt